# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

version: 2
project_name: tandem
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
archives:
  - formats: [tar.gz]
    name_template: >-
      {{ tolower .ProjectName }}_
      {{- tolower .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats: [zip]
    wrap_in_directory: "{{ tolower .ProjectName }}_tmp"
    files:
      - src: tandem.example.env
        dst: tandem.example.env
      - src: .tandem/swarm.json
        dst: swarm.json
      - src: LICENSE
        dst: LICENSE
      - src: README.md
        dst: README.md
report_sizes: true
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
